# Generated by Django 5.0 on 2026-09-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
