# Generated by Django 5.0 on 2026-10-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_image_car_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste normal image URL or Google Drive sharing link', null=True),
        ),
    ]
