# Generated by Django 5.0 on 2026-10-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
