# Generated by Django 5.0 on 2026-10-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='insurance_valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
