# Generated by Django 5.0 on 2026-10-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_insurance_valid_upto_car_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_url_10',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image_url_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image_url_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image_url_4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image_url_5',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image_url_6',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image_url_7',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image_url_8',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='image_url_9',
            field=models.URLField(blank=True, null=True),
        ),
    ]
